apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: lanchonete_app
  template:
    metadata:
      labels:
        app: lanchonete_app
    spec:
      containers:
        - name: lanchonete-app-container
          image: lanchonete_app:latest
          imagePullPolicy: Never         # <- adiciona aqui 
          ports:
            - containerPort: 8000
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: APP_PORT
              value: "8000"
            - name: DB_HOST
              value: "db-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
