apiVersion: v1
kind: Secret
metadata:
  name: lanchonete-app-secret
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "lanchonete"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/lanchonete"