apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: lanchonete_app    
  ports:
    - name: http
      protocol: TCP
      port: 80              
      targetPort: 8000      # Porta que o container lanchonete-app-container escuta
      # nodePort: opcional
  type: NodePort