"""corrige campo categoria em produto

Revision ID: b6aea9f7011f
Revises: 9037352ae04b
Create Date: 2025-04-17 22:19:34.168415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6aea9f7011f'
down_revision: Union[str, None] = '9037352ae04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('categoria', sa.String(), nullable=False, server_default='Lanche'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'categoria')
    # ### end Alembic commands ###
