services:
  app:
    build:
      context: ./bin/webserver
      dockerfile: Dockerfile
    container_name: lanchonete_app
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ../:/app
    env_file:
      - .env
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    build:
      context: ./bin/postgresql
      dockerfile: Dockerfile
    container_name: lanchonete_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data